"""empty message

Revision ID: 862f6d1ce482
Revises: a2dbf49bd2c7
Create Date: 2020-12-06 21:27:08.599500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862f6d1ce482'
down_revision = 'a2dbf49bd2c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
