"""empty message

Revision ID: 8650c0f177af
Revises: 862f6d1ce482
Create Date: 2020-12-06 21:29:10.600236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8650c0f177af'
down_revision = '862f6d1ce482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
