"""empty message

Revision ID: 94615488cef0
Revises: 5010173ceef9
Create Date: 2020-12-06 20:50:21.837457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94615488cef0'
down_revision = '5010173ceef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professors', sa.Column('password', sa.String(), nullable=True))
    op.add_column('professors', sa.Column('username', sa.String(), nullable=True))
    op.add_column('students', sa.Column('password', sa.String(), nullable=True))
    op.add_column('students', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'username')
    op.drop_column('students', 'password')
    op.drop_column('professors', 'username')
    op.drop_column('professors', 'password')
    # ### end Alembic commands ###
