"""empty message

Revision ID: 97522ae2384c
Revises: 
Create Date: 2020-11-29 12:50:26.422372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97522ae2384c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authorId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['authorId'], ['professors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('courseId', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['courseId'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['studentId'], ['students.id'], ),
    sa.PrimaryKeyConstraint('studentId', 'courseId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    op.drop_table('courses')
    op.drop_table('students')
    op.drop_table('professors')
    # ### end Alembic commands ###
