"""empty message

Revision ID: a2dbf49bd2c7
Revises: 94615488cef0
Create Date: 2020-12-06 21:00:56.341534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2dbf49bd2c7'
down_revision = '94615488cef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('professorId', sa.Integer(), nullable=True),
    sa.Column('studentId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['professorId'], ['professors.id'], ),
    sa.ForeignKeyConstraint(['studentId'], ['students.id'], ),
    sa.PrimaryKeyConstraint('username')
    )
    op.drop_column('professors', 'password')
    op.drop_column('professors', 'username')
    op.drop_column('students', 'password')
    op.drop_column('students', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('professors', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('professors', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('users')
    # ### end Alembic commands ###
