"""empty message

Revision ID: a6af536583a2
Revises: fb3b56237cd5
Create Date: 2020-12-08 18:38:16.427560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6af536583a2'
down_revision = 'fb3b56237cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professors', sa.Column('owner', sa.String(), nullable=True))
    op.drop_constraint('professors_username_fkey', 'professors', type_='foreignkey')
    op.create_foreign_key(None, 'professors', 'users', ['owner'], ['username'])
    op.drop_column('professors', 'username')
    op.add_column('students', sa.Column('owner', sa.String(), nullable=True))
    op.drop_constraint('students_username_fkey', 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'users', ['owner'], ['username'])
    op.drop_column('students', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key('students_username_fkey', 'students', 'users', ['username'], ['username'])
    op.drop_column('students', 'owner')
    op.add_column('professors', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'professors', type_='foreignkey')
    op.create_foreign_key('professors_username_fkey', 'professors', 'users', ['username'], ['username'])
    op.drop_column('professors', 'owner')
    # ### end Alembic commands ###
