"""empty message

Revision ID: c3e9142692a2
Revises: 8650c0f177af
Create Date: 2020-12-06 21:50:03.279452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e9142692a2'
down_revision = '8650c0f177af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
