"""empty message

Revision ID: c73592926d88
Revises: 97522ae2384c
Create Date: 2020-11-29 13:50:45.979667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73592926d88'
down_revision = '97522ae2384c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentsAndCourses',
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('courseId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courseId'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['studentId'], ['students.id'], ),
    sa.PrimaryKeyConstraint('studentId', 'courseId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studentsAndCourses')
    # ### end Alembic commands ###
