"""empty message

Revision ID: d7b22b565fad
Revises: c73592926d88
Create Date: 2020-11-29 16:59:47.811601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b22b565fad'
down_revision = 'c73592926d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_student_relation',
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], )
    )
    op.drop_table('studentsAndCourses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentsAndCourses',
    sa.Column('studentId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('courseId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['courseId'], ['courses.id'], name='studentsAndCourses_courseId_fkey'),
    sa.ForeignKeyConstraint(['studentId'], ['students.id'], name='studentsAndCourses_studentId_fkey'),
    sa.PrimaryKeyConstraint('studentId', 'courseId', name='studentsAndCourses_pkey')
    )
    op.drop_table('course_student_relation')
    # ### end Alembic commands ###
