"""empty message

Revision ID: fb3b56237cd5
Revises: a55c6c16765a
Create Date: 2020-12-08 18:37:26.172253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3b56237cd5'
down_revision = 'a55c6c16765a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_studentId_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_professorId_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'professorId')
    op.drop_column('users', 'studentId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('studentId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('professorId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_professorId_fkey', 'users', 'professors', ['professorId'], ['id'])
    op.create_foreign_key('users_studentId_fkey', 'users', 'students', ['studentId'], ['id'])
    # ### end Alembic commands ###
